# Generated by Django 5.1.2 on 2024-10-26 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization_mgmt', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCharter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='CostUnit',
            fields=[
                ('cost_unit_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100, unique=True)),
                ('fa_title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CostType',
            fields=[
                ('cost_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('fa_title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project_mgmt.costunit')),
            ],
        ),
        migrations.CreateModel(
            name='IssueCategory',
            fields=[
                ('issue_category_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectCalendar',
            fields=[
                ('project_calnedar_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_projects', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep_projects', to='organization_mgmt.department')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='manager_projects', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='updated_projects', to=settings.AUTH_USER_MODEL)),
                ('calendar', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project_mgmt.projectcalendar')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectIssue',
            fields=[
                ('project_issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('document', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('solvable', 'قابل حل'), ('unsolvable', 'غیر قابل حل')], max_length=50)),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'در حال اقدام'), ('rejected', 'مرتفع شده'), ('approved', 'مرتفع نشده')], max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project_mgmt.issuecategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_project_issues', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_mgmt.project')),
                ('responisble', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='responsible_project_issues', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('project_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project_mgmt.projectstatus'),
        ),
        migrations.CreateModel(
            name='ProjectType',
            fields=[
                ('project_type_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('fa_title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='projects', to='project_mgmt.projecttype'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('is_summery', models.BooleanField(default=0)),
                ('start_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('actual_progress', models.DecimalField(decimal_places=2, max_digits=5)),
                ('cost', models.PositiveBigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='my_assigments', to=settings.AUTH_USER_MODEL)),
                ('cost_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project_mgmt.costtype')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='my_created_tasks', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='childs', to='project_mgmt.task')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project_mgmt.project')),
                ('status_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='my_approval_assignments', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='my_updated_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HistoryAndTransActions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_actual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('to_actual', models.DecimalField(decimal_places=2, max_digits=5)),
                ('approval_status', models.TextField(choices=[('pending', 'در حال بررسی'), ('rejected', 'رد شده'), ('approved', 'تایید شده')])),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('submbitter_description', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(auto_now_add=True)),
                ('approver_description', models.TextField(blank=True)),
                ('document', models.TextField(blank=True, max_length=150)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='approver_transactions', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='submitter_transactions', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='project_mgmt.task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskIssue',
            fields=[
                ('task_issue_id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('document', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('solvable', 'قابل حل'), ('unsolvable', 'غیر قابل حل')], max_length=50)),
                ('deadline', models.DateTimeField()),
                ('status', models.CharField(choices=[('pending', 'در حال اقدام'), ('rejected', 'مرتفع شده'), ('approved', 'مرتفع نشده')], max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='project_mgmt.issuecategory')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_task_issues', to=settings.AUTH_USER_MODEL)),
                ('responisble', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='responsible_task_issues', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project_mgmt.task')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingDay',
            fields=[
                ('working_day_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(choices=[('Saturday', 'شنبه'), ('Sunday', 'یکشنبه'), ('Monday', 'دوشنبه'), ('Tuesday', 'سه شنبه'), ('Wednesday', 'چهارشنبه'), ('Thursday', 'پنج شنبه')], max_length=50)),
                ('start_at', models.TimeField()),
                ('end_at', models.TimeField()),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='working_days', to='project_mgmt.projectcalendar')),
            ],
        ),
    ]
