# Generated by Django 5.1.2 on 2024-10-28 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectcalendar',
            old_name='project_calnedar_id',
            new_name='project_calendar_id',
        ),
    ]
